### ISSUE TITLE
`segmentation.m` unable to find `skel_file`

### ISSUE THREAD

**Issue by HowcanoeWang** [suptimq/Apple_Crop_Potential_Prediction#3]
https://github.com/suptimq/AppleQSM/blob/f12e99e0214cff324a37d882bb251b7c820a06f6/code/segmentation.m#L14

need change `'_contract_*_skeleton.mat'` to `'*_contract_*_skeleton.mat'`

**Comment by suptimq** [comment]
Thanks for pointing it out!
